- alias: Porch Light
  id: porch_light
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: light.porch_light
    service: light.turn_on
- alias: Porch Light Off
  id: porch_light_off
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: light.porch_light
    service: light.turn_off
- alias: Countertop lights
  id: countertop_lights
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.countertop_lights
    state: 'off'
  action:
  - data: {}
    entity_id: light.countertop_lights
    service: light.turn_on
- alias: Countertop Lights Off
  id: countertop_lights_off
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    for: 00:03:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.countertop_lights
    service: light.turn_off
- alias: Enable Zigbee joining
  id: enable_zigbee_join
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join
- alias: Disable Zigbee joining
  id: disable_zigbee_join
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
- alias: Disable Zigbee joining by timer
  id: disable_zigbee_join_timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
- alias: Start HomeKit
  id: start_homekit
  trigger:
    platform: homeassistant
    event: start
  action:
  - delay: 00:05
  - service: homekit.start
- alias: Washer Filling
  id: washer_state_filling
  description: Set washer state to filling when power detected
  trigger:
  - above: '3.5'
    entity_id: sensor.pigtail_switch_power
    platform: numeric_state
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.washing_machine_state
      state: Empty
    - condition: state
      entity_id: input_select.washing_machine_state
      state: Clean
  action:
  - data:
      entity_id: input_select.washing_machine_state
      option: Filling
    service: input_select.select_option
- alias: Washer Washing
  id: washer_state_washing
  description: Set washer state to filling when power detected
  trigger:
  - above: '100'
    entity_id: sensor.pigtail_switch_power
    platform: numeric_state
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.washing_machine_state
      state: Empty
    - condition: state
      entity_id: input_select.washing_machine_state
      state: Filling
  action:
  - data:
      entity_id: input_select.washing_machine_state
      option: Washing
    service: input_select.select_option
- alias: Washer State Clean
  id: washer_state_clean
  description: Set washer state to clean when no power detected
  trigger:
  - platform: numeric_state
    entity_id: sensor.pigtail_switch_power
    below: 2
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.washing_machine_state
      state: Washing
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.washing_machine_state
      option: Clean
- id: washer_state_empty
  alias: Washer State Empty
  description: Set washer state to empty when lid opened after a run
  trigger:
  - entity_id: binary_sensor.washer_lid
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.washing_machine_state
      state: Clean
  action:
  - data:
      entity_id: input_select.washing_machine_state
      option: Empty
    service: input_select.select_option
