- platform: wyzesense
  device: auto

- platform: template
  sensors: 
    back_door:
      friendly_name: "Back Door"
      device_class: door
      value_template: "{{ is_state('sensor.back_door_alarm_level', '255') }}"
    front_door:
      friendly_name: "Front Door"
      device_class: door
      value_template: "{{ is_state('sensor.front_door_alarm_level', '255') }}"