homeassistant:
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

logbook:
system_health:
config:
updater:
sun:
map:
mobile_app:
history: !include history.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml
binary_sensor: !include binary_sensor.yaml
light: !include lights.yaml
timer: !include timers.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
homekit: !include homekit.yaml

ecobee:
  api_key: !secret ecobee_api_key

recorder:
  purge_keep_days: 60
  db_url: mssql+pyodbc://HASSIO:Automagical1@192.168.1.222/HASSIO?charset=utf8;DRIVER={FreeTDS};Port=1433;

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret network_key

