homeassistant:
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include customize.yaml
  external_url: !secret cflare_base_url

frontend:
  themes: !include_dir_merge_named themes

logbook:
system_health:
config:
updater:
sun:
map:
mobile_app:
history: !include history.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml
binary_sensor: !include binary_sensor.yaml
light: !include lights.yaml
timer: !include timers.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
homekit: !include homekit.yaml

recorder:
  purge_keep_days: 60
  db_url: !secret sql_connection

http:
  use_x_forwarded_for: True
  trusted_proxies:
   - 127.0.0.1
   - 192.168.1.0/24
  ssl_certificate: !secret cflare_ssl_pem
  ssl_key: !secret cflare_ssl_key

cloudflare:
  email: !secret cflare_email
  api_key: !secret cflare_api_key
  zone: !secret cflare_zone
  records:
    - ha
    - www

# Text to speech
tts:
  - platform: google_translate
