homeassistant:
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include customize.yaml
  external_url: !secret cflare_base_url
  internal_url: !secret internal_url

frontend:
  themes: !include_dir_merge_named themes

logbook:
system_health:
config:
updater:
sun:
map:
mobile_app:
history: !include history.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include template_sensors.yaml
zone: !include zones.yaml
# binary_sensor: !include binary_sensor.yaml
light: !include lights.yaml
timer: !include timers.yaml
input_boolean: !include input_booleans.yaml
input_datetime: !include input_datetimes.yaml
input_select: !include input_selects.yaml
homekit: !include homekit.yaml
notify: !include notifications.yaml
python_script:

recorder:
  purge_keep_days: 60
  db_url: !secret sql_connection

http:
  use_x_forwarded_for: True
  trusted_proxies:
   - 127.0.0.1
   - 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: !secret cflare_ssl_pem
  ssl_key: !secret cflare_ssl_key

tts:
  - platform: google_translate

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_code
    arming_time: 30
    delay_time: 50
    trigger_time: 30
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 15
      delay_time: 0

logger:
  default: info

hacs:
  token: !secret hacs_token

# panel_iframe:
#   zwavejs:
#     title: 'ZwaveJS'
#     url: 'http://192.168.1.101:8092'
#     icon: 'mdi:z-wave'
#   zigbee:
#     title: 'Zigbee'
#     url: 'http://192.168.1.101:8099'
#     icon: 'mdi:zigbee'