- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
- platform: statistics
  entity_id: sensor.laundry_aqara_temperature
  name: Laundry_Temp_Stats

# - platform: rest
#   resource: https://www.purpleair.com/json?show=12835
#   name: Air Quality