- alias: Countertop lights
  id: countertop_lights
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.all_countertop_lights
    state: 'off'
  action:
  - data: {}
    entity_id: light.all_countertop_lights
    service: light.turn_on
- alias: Countertop Lights Off
  id: countertop_lights_off
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    for: 00:03:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.all_countertop_lights
    service: light.turn_off

- alias: Hutch Light On
  id: hutch_light_on
  description: ''
  trigger:
  - at: '08:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: light.hutch_lights
    service: light.turn_on

- alias: Hutch Light Off
  id: hutch_light_off
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: light.hutch_lights
    service: light.turn_off