- alias: Garage open late
  id: garage_open_late
  description: ''
  trigger:
  - at: '20:00:00'
    platform: time
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.r_garage_sensor
      state: 'on'
    - condition: state
      entity_id: binary_sensor.k_garage_sensor
      state: 'on'
  action:
  - service: notify.mobile_app_rphone
    data:
      title: Garage left open
      message: Garage door open
      data:
          push:
            sound:
              name: default
              critical: 1
              volume: 0.3

- alias: Shed open late
  id: shed_open_late
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.shed_door
    state: 'on'
  action:
  - service: notify.mobile_app_rphone
    data:
      title: Shed left open
      message: Shed door open!!!
      data:
          push:
            sound:
              name: default
              critical: 1
              volume: 0.3

- id: 'Button_Notify'
  alias: Notification
  trigger:
  - entity_id: sensor.call_button_click
    platform: state
    to: single
  action:
    - service: notify.mobile_app_rphone
      data:
        title: Button Pressed
        message: Help me I can't get up!!!
        data:
            push:
              sound:
                name: default
                critical: 1
                volume: 0.3