- alias: Garage open late
  id: garage_open_late
  description: ''
  trigger:
  - at: '20:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: group.garage_doors
    state: 'on'
  action:
  - service: notify.mobile_app_rphone
    data:
      title: Garage left open
      message: >
        {% for entity in expand(state_attr('group.garage_doors','entity_id')) -%}
        {%if states(entity.entity_id)%} {{ state_attr(entity.entity_id,'friendly_name') }} is open. 
        {%-endif%}
        {%endfor%}
      data:
          push:
            sound:
              name: default
              critical: 1
              volume: 0.3
            vibrationPattern: 100, 1000, 100, 1000, 100

- alias: Shed open late
  id: shed_open_late
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.shed_door
    state: 'on'
  action:
  - service: notify.mobile_app_rphone
    data:
      title: Shed left open
      message: Shed door open!!!
      data:
          push:
            sound:
              name: default
              critical: 1
              volume: 0.3

- id: 'Button_Notify'
  alias: Notification
  trigger:
  - entity_id: sensor.smart_button_click
    platform: state
    to: single
  action:
    - service: notify.mobile_app_rphone
      data:
        title: Button Pressed
        message: Help me I can't get up!!!
        data:
            push:
              sound:
                name: default
                critical: 1
                volume: 0.3

- id: 'UPS_Discharging'
  alias: UPS Discharging Notification
  trigger:
  - entity_id: sensor.closet_ups_status
    platform: state
    to: Online Battery Discharging
  action:
    - service: notify.mobile_app_rphone
      data:
        title: Power Failure
        message: UPS State is {{ states.sensor.closet_ups_status.state }}.
        data:
            push:
              sound:
                name: default
                critical: 1
                volume: 0.3