esphome:
  name: hutch_lights
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret ssidpassword
  power_save_mode: none
  fast_connect: true
  reboot_timeout:
    minutes: 15
  # Static IP
  manual_ip:
    static_ip: 192.168.1.104
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    
  ap:
    ssid: "Hutch Lights Fallback Hotspot"
    password: !secret password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password
#ESPeasy testtemp
#RGBWarm
output:
  # - platform: esp8266_pwm
  #   pin: 12
  #   frequency: 1000 Hz
  #   id: pwm_b
  # - platform: esp8266_pwm
  #   pin: 15
  #   frequency: 1000 Hz
  #   id: pwm_g
  # - platform: esp8266_pwm
  #   pin: 13
  #   frequency: 1000 Hz
  #   id: pwm_r
  # - platform: esp8266_pwm
  #   pin: 14
  #   frequency: 1000 Hz
  #   id: pwm_w
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_w2

light:
  - platform: monochromatic
    name: "Hutch Lights"
    output: pwm_w2
    effects:
      - pulse:
          name: Fast Pulse
          transition_length: 0.25s
          update_interval: 0.5s
      - pulse:
          name: Slow Pulse
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
    #   - strobe:
      - flicker:
          name: Flicker
          alpha: 90%
          intensity: 3.5%

sensor:
  - platform: wifi_signal
    name: "Hutch Lights WiFi Signal"
    update_interval: 600s
