esphome:
  name: sump_pump
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret ssidpassword
  power_save_mode: none
  fast_connect: true
  reboot_timeout:
    minutes: 3
  # Static IP
  manual_ip:
    static_ip: 192.168.1.108
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    
  ap:
    ssid: "Sump Pump Fallback Hotspot"
    password: !secret password

# Enable logging
logger:

uart:
  rx_pin: RX
  baud_rate: 4800

api:
  password: !secret password

ota:
  password: !secret password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sump Pump Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sump Pump Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

sensor:
  - platform: cse7766
    update_interval: 2s
    current:
      name: "Sump Pump Current"
      filters:
        - or:
          - throttle: 60s
          - delta: 0.5
    voltage:
      name: "Sump Pump Voltage"
      filters:
        - or:
          - throttle: 60s
          - delta: 1
    power:
      name: "Sump Pump Power"
      filters:
        - or:
          - throttle: 60s
          - delta: 5
  - platform: wifi_signal
    name: "Sump Pump WiFi Signal"
    update_interval: 600s

status_led:
  pin:
    number: GPIO13
